version: '3.9'

services:
  db:
    container_name: torquemate-db
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: torquemate
      POSTGRES_USER: torquemate
      POSTGRES_PASSWORD: fordevonly
    volumes:
      - /tmp/migrations/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql:rshared

  adminer:
    container_name: torquemate-adminer
    image: adminer
    restart: always
    ports:
      - 5145:8080
    depends_on:
      - db

  torquemate:
    container_name: torquemate
    image: ghcr.io/jeeyo/torquemate:latest
    restart: always
    environment:
      ConnectionStrings__NpgsqlTorqueDatabase: Host=db; Port=5432; Database=torquemate; Username=torquemate; Password=fordevonly; Include Error Detail=true;
    volumes:
      - /tmp/migrations/:/migrations/:rshared
    ports:
      - 5147:8080
    depends_on:
      - db
