version: '3.9'

services:
  db:
    container_name: torquemate-db
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: torquemate
      POSTGRES_USER: torquemate
      POSTGRES_PASSWORD: fordevonly
    volumes:
      - ./migrations/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
    ports:
      - 5432:5432

  grafana:
    container_name: torquemate-grafana
    image: grafana/grafana-oss:10.3.4
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  torquemate:
    container_name: torquemate
    image: ghcr.io/jeeyo/torquemate:latest
    restart: always
    environment:
      ConnectionStrings__NpgsqlTorqueDatabase: Host=db; Port=5432; Database=torquemate; Username=torquemate; Password=fordevonly; Include Error Detail=true;
    ports:
      - 5147:8080
    depends_on:
      - db
