apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "torquemate.fullname" . }}
  namespace: {{ include "torquemate.namespace" . }}
  labels:
    {{- include "torquemate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "torquemate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "torquemate.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_HTTP_PORTS
              values: 80
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
