apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "torquemate.fullname" . }}
  labels:
    {{- include "torquemate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "torquemate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "torquemate.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: 80
            - name: ConnectionStrings__NpgsqlTorqueDatabase
              value: Host={{ .Values.database.host }}; Port={{ .Values.database.port }}; Database={{ .Values.database.database }}; Username={{ .Values.database.username }}; Password={{ .Values.database.password }}; Include Error Detail=true;
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
